ALTER TYPE "PaymentFrequency" ADD VALUE IF NOT EXISTS 'ANUAL';

ALTER TABLE "Quote"
    ADD COLUMN "totalAnnual" DECIMAL(65,30) NOT NULL DEFAULT 0,
    ADD COLUMN "taxAmountAnnual" DECIMAL(65,30) NOT NULL DEFAULT 0;
